### ISSUE TITLE
bug: depth cache is crashing

### ISSUE THREAD

**Issue by mor-o** [jaggedsoft/node-binance-api#207]
**Short Description:**
node-binance-api crashed after using depth cache for long period of time.

**Platform:**
 windows

**node version:**
- 8.9.4

**Long descrption**
in the logs below you can see it gets 504 from the server and keeps trying. 
at some point it seems to be losing sync for some symbols and than the exception occurs.
this is the second time it happens but this time i had it on verbose.
both times it append after binance listed a new coin. 
could that be the reason for the exception?
btw i am working with release v0.4.29
  
```
2018-5-9 10:09:06 INFO: binance:WebSocket error: 3837619344 Unexpected server response: 504
2018-5-9 10:09:06 INFO: binance:WebSocket closed: 3837619344 (1006)
2018-5-9 10:09:06 INFO: binance:WebSocket reconnecting: 3837619344...
2018-5-9 10:09:06 INFO: binance:CombinedStream: Subscribed to [3837619344] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/btcusdt@depth
2018-5-9 10:09:10 INFO: binance:depthHandler: [INSBTC] Skip count exceeded. The depth cache is out of sync.
2018-5-9 10:09:10 INFO: binance:CombinedStream: Subscribed to [3837619344] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/btcusdt@depth
2018-5-9 10:09:10 INFO: binance:depthHandler: [ASTBTC] Skip count exceeded. The depth cache is out of sync.
2018-5-9 10:09:10 INFO: binance:CombinedStream: Subscribed to [3837619344] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/btcusdt@depth
2018-5-9 10:09:24 INFO: binance:depthHandler: [EVXBTC] Incorrect update ID. The depth cache is out of sync.
2018-5-9 10:09:24 INFO: binance:CombinedStream: Subscribed to [3837619344] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/btcusdt@depth
Debugger attached.
node_modules\node-binance-api\node-binance-api.js:1520
                        context.messageQueue = context.messageQueue.filter(depth => depth.u > context.snapshotUpdateId);
                                                                    ^

TypeError: Cannot read property 'filter' of undefined
    at node_modules\node-binance-api\node-binance-api.js:1520:69
    at Request._callback (node_modules\node-binance-api\node-binance-api.js:76:20)
    at Request.self.callback (node_modules\node-binance-api\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (node_modules\node-binance-api\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (node_modules\node-binance-api\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

please check why this happens
thank you:)

**Comment by dmzoneill** [comment]
might be related to 
https://github.com/jaggedsoft/node-binance-api/issues/208

Binance closes websockets after 24hrs, do you have any more information on when this happens?

**Comment by mor-o** [comment]
```
2018-5-14 12:22:11 INFO: binance:depthHandler: [LTCBTC] Incorrect update ID. The depth cache is out of sync.
2018-5-14 12:22:11 INFO: binance:CombinedStream: Subscribed to [2785022752] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/repbtc@depth/btcusdt@depth
2018-5-14 12:22:14 INFO: binance:depthHandler: [CMTBTC] Incorrect update ID. The depth cache is out of sync.
2018-5-14 12:22:14 INFO: binance:CombinedStream: Subscribed to [2785022752] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/repbtc@depth/btcusdt@depth
2018-5-14 12:22:16 INFO: binance:depthHandler: [LTCBTC] Incorrect update ID. The depth cache is out of sync.
2018-5-14 12:22:16 INFO: binance:CombinedStream: Subscribed to [2785022752] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/repbtc@depth/btcusdt@depth
2018-5-14 12:22:16 INFO: binance:depthHandler: [RLCBTC] Skip count exceeded. The depth cache is out of sync.
2018-5-14 12:22:16 INFO: binance:CombinedStream: Subscribed to [2785022752] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/repbtc@depth/btcusdt@depth
2018-5-14 12:22:16 INFO: binance:depthHandler: [ARKBTC] Skip count exceeded. The depth cache is out of sync.
2018-5-14 12:22:16 INFO: binance:CombinedStream: Subscribed to [2785022752] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/repbtc@depth/btcusdt@depth
2018-5-14 12:22:17 INFO: binance:depthHandler: [ZECBTC] Incorrect update ID. The depth cache is out of sync.
2018-5-14 12:22:17 INFO: binance:CombinedStream: Subscribed to [2785022752] ethbtc@depth/ltcbtc@depth/bnbbtc@depth/neobtc@depth/bccbtc@depth/gasbtc@depth/hsrbtc@depth/mcobtc@depth/wtcbtc@depth/lrcbtc@depth/qtumbtc@depth/yoyobtc@depth/omgbtc@depth/zrxbtc@depth/stratbtc@depth/snglsbtc@depth/bqxbtc@depth/kncbtc@depth/funbtc@depth/snmbtc@depth/iotabtc@depth/linkbtc@depth/xvgbtc@depth/saltbtc@depth/mdabtc@depth/mtlbtc@depth/subbtc@depth/eosbtc@depth/sntbtc@depth/etcbtc@depth/mthbtc@depth/engbtc@depth/dntbtc@depth/zecbtc@depth/bntbtc@depth/astbtc@depth/dashbtc@depth/oaxbtc@depth/icnbtc@depth/btgbtc@depth/evxbtc@depth/reqbtc@depth/vibbtc@depth/trxbtc@depth/powrbtc@depth/arkbtc@depth/xrpbtc@depth/modbtc@depth/enjbtc@depth/storjbtc@depth/venbtc@depth/kmdbtc@depth/rcnbtc@depth/nulsbtc@depth/rdnbtc@depth/xmrbtc@depth/dltbtc@depth/ambbtc@depth/batbtc@depth/bcptbtc@depth/arnbtc@depth/gvtbtc@depth/cdtbtc@depth/gxsbtc@depth/poebtc@depth/qspbtc@depth/btsbtc@depth/xzcbtc@depth/lskbtc@depth/tntbtc@depth/fuelbtc@depth/manabtc@depth/bcdbtc@depth/dgdbtc@depth/adxbtc@depth/adabtc@depth/pptbtc@depth/cmtbtc@depth/xlmbtc@depth/cndbtc@depth/lendbtc@depth/wabibtc@depth/tnbbtc@depth/wavesbtc@depth/gtobtc@depth/icxbtc@depth/ostbtc@depth/elfbtc@depth/aionbtc@depth/neblbtc@depth/brdbtc@depth/edobtc@depth/wingsbtc@depth/navbtc@depth/lunbtc@depth/trigbtc@depth/appcbtc@depth/vibebtc@depth/rlcbtc@depth/insbtc@depth/pivxbtc@depth/iostbtc@depth/chatbtc@depth/steembtc@depth/nanobtc@depth/viabtc@depth/blzbtc@depth/aebtc@depth/rpxbtc@depth/ncashbtc@depth/poabtc@depth/zilbtc@depth/ontbtc@depth/stormbtc@depth/xembtc@depth/wprbtc@depth/qlcbtc@depth/sysbtc@depth/grsbtc@depth/cloakbtc@depth/repbtc@depth/btcusdt@depth
Debugger attached.
node_modules\node-binance-api\node-binance-api.js:1638
                        context.messageQueue = context.messageQueue.filter(depth => depth.u > context.snapshotUpdateId);
                                                                    ^

TypeError: Cannot read property 'filter' of undefined
    at node_modules\node-binance-api\node-binance-api.js:1638:69
    at Request._callback (node_modules\node-binance-api\node-binance-api.js:108:61)
    at Request.self.callback (node_modules\node-binance-api\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (node_modules\node-binance-api\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (node_modules\node-binance-api\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Waiting for the debugger to disconnect...
```
