### ISSUE TITLE
Invalid Test API Credentials

### ISSUE THREAD

**Issue by bmino** [jaggedsoft/node-binance-api#241]
**Invalid Test API Credentials**
- bug: Unit tests fail

**Short Description:**
- Unit tests that rely on the provided API credentials fail due to them being invalid
  
**Platform:**
- linux

**node version:**
- 9.11.2

**Long descrption**
- Unit tests that rely on the provided API credentials fail due to them being invalid

**code**
```
npm test
```

**result**
17 unit tests are failing
<details> 
  <summary>Failing Unit Tests (Expand Me)</summary>

  1) Balances
       Get the balances in the account:
     Uncaught AssertionError: should be null
      at binance.balance (test.js:121:7)
      at /home/brandon/github/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1370:33
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  2) Buy order advanced
       Attempt to buy BNB specifying order type:
     Uncaught AssertionError: Unspecified AssertionError
      at binance.buy (test.js:272:7)
      at /home/brandon/github/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:256:29
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  3) Cancel order
       Attempt to cancel an order:
     Uncaught AssertionError: Unspecified AssertionError
      at binance.cancel (test.js:313:7)
      at /home/brandon/github/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1105:49
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  4) Cancel orders
       Attempt to cancel all orders given a symbol:
     Uncaught TypeError: json is not iterable
      at /home/brandon/github/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1148:34
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  5) Open Orders
       Attempt to show all orders to ETHBTC:
     Uncaught AssertionError: should be null
      at binance.openOrders (test.js:348:7)
      at /home/brandon/github/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1133:33
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  6) Open Orders
       Attempt to show all orders for all symbols:
     Uncaught AssertionError: should be null
      at binance.openOrders (test.js:364:7)
      at /home/brandon/github/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1133:33
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  7) Order status
       Attempt to get the order status for a given order id:
     Uncaught AssertionError: Unspecified AssertionError
      at binance.orderStatus (test.js:384:7)
      at /home/brandon/github/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1120:49
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  8) trades
       Attempt get all trade history for given symbol:
     Uncaught AssertionError: should be null
      at binance.trades (test.js:401:7)
      at /home/brandon/github/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1384:49
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  9) Orders
       Attempt get all orders for given symbol:
     Uncaught AssertionError: should be null
      at binance.allOrders (test.js:419:7)
      at /home/brandon/github/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1168:49
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  10) Withdraw
       Attempt to withdraw BNB to another address:
     Uncaught AssertionError: Unspecified AssertionError
      at binance.withdraw (test.js:673:7)
      at Request._callback (node-binance-api.js:112:14)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  11) Withdraw
       Attempt to withdraw BNB to another address with address tag:
     Uncaught AssertionError: Unspecified AssertionError
      at binance.withdraw (test.js:689:7)
      at Request._callback (node-binance-api.js:112:14)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  12) Withdraw history
       Attempt to get withdraw history for BTC:
     Uncaught AssertionError: should have key withdrawList
      at binance.withdrawHistory (test.js:706:7)
      at Request._callback (node-binance-api.js:112:14)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  13) Withdraw history
       Attempt to get withdraw history for all assets:
     Uncaught AssertionError: should have key withdrawList
      at binance.withdrawHistory (test.js:722:7)
      at Request._callback (node-binance-api.js:112:14)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  14) Deposit history
       Attempt to get deposit history for all assets:
     Uncaught AssertionError: should have key depositList
      at binance.depositHistory (test.js:741:7)
      at Request._callback (node-binance-api.js:112:14)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  15) Deposit address
       Attempt to get deposit address for BNB:
     Uncaught AssertionError: should have key address
      at binance.depositAddress (test.js:759:7)
      at Request._callback (node-binance-api.js:112:14)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  16) Account
       Attempt to get account information:
     Uncaught AssertionError: should be null
      at binance.account (test.js:808:7)
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  17) Historical Trades
       Attempt get Historical Trades for a given symbol:
     Uncaught AssertionError: should be null
      at binance.historicalTrades (test.js:881:7)
      at Request._callback (node-binance-api.js:110:61)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1157:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

</details>

**Comment by dmzoneill** [comment]
@jaggedsoft 
@bmino 

resosolved
