### ISSUE TITLE
TypeError: binance.options is not a function

### ISSUE THREAD

**Issue by Roy5000** [jaggedsoft/node-binance-api#243]
Unable to run getting started code,  running the code will return message 'TypeError: binance.options is not a function'.

Reinstall of npm package did not solve this issue.  Do I need to define the options function separately?

**code**
```
const binance = require('node-binance-api');
binance.options({
  APIKEY: '<key>',
  APISECRET: '<secret>',
  useServerTime: true, // If you get timestamp errors, synchronize to server time at startup
  test: true // If you want to use sandbox mode where orders are simulated
});

```

**result**
```
C:\Users\name\Documents\APP\app2.js:6
binance.options({
        ^

TypeError: binance.options is not a function
    at Object.<anonymous> (C:\Users\rvan17\Documents\APP\app2.js:6:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by jaggedsoft** [comment]
That should work, but this would be an alternative:

```js
const Binance = require('node-binance-api');
const binance = new Binance().options({
  APIKEY: '<key>',
  APISECRET: '<secret>',
  useServerTime: true
});
```

**Comment by dakovi** [comment]
I also had to use the alternative above when switching to the newest version because of this error. Not much of a problem but the readme / initial documentation isn't very clear on that if you just want to run a single instance.

**Comment by Roy5000** [comment]
Thank you Jaggedsoft!  The alternative code works perfect!

**Comment by sandybradley** [comment]
Hi,
This alternative did not work for me.

  const binance = new Binance().options({
                  ^

TypeError: Binance is not a constructor
    at C:\crypto-exchanges\BinanceMA.js:6:19
    at Object.<anonymous> (C:\crypto-exchanges\BinanceMA.js:326:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by jaggedsoft** [comment]
@sandybradley above that line did you add `const Binance = require('node-binance-api');`

**Comment by sandybradley** [comment]
Thanks for the fast response @jaggedsoft .
Yes, I copied your example above.
