### ISSUE TITLE
set proxy ERROR  https_proxy

### ISSUE THREAD

**Issue by Qasemt** [jaggedsoft/node-binance-api#291]
**Title**
- bug: set proxy ERROR

  
**Platform:**
- windows

**node version:**
- 8

**Long descrption**
set https_proxy=http://128.199.51.183:3128  befor run in command prompt

***code****
```
const bitprophet = require('bitprophet')

bitprophet.options({
    binance: {
        key: "9xxxxxrts",
        secret: "xxxx"
    },
    telegram: {
        chatId: "qtradingview_bot",
        token: "xxxx"
    },
   
})

bitprophet.start()
```

**result**
```
{
   "result":"C:\Users\AT\Desktop\yt\node_modules\node-binance-api\node-binance-api.js:352
            if ( options.verbose ) options.log('using proxy server ' + proxy);
            ^

ReferenceError: options is not defined
    at subscribe (C:\Users\AT\Desktop\yt\node_modules\node-binance-api\node-binance-api.js:352:13)
    at Object.chart (C:\Users\AT\Desktop\yt\node_modules\node-binance-api\node-binance-api.js:1630:36)
    at Object.startChartUpdate (C:\Users\AT\Desktop\yt\node_modules\bitprophet\exchange_utils.js:173:22)
    at create.startChartUpdates (C:\Users\AT\Desktop\yt\node_modules\bitprophet\pair_generator.js:118:14)
    at create.addWatcherChartUpdates (C:\Users\AT\Desktop\yt\node_modules\bitprophet\pair_generator.js:153:11)
    at C:\Users\AT\Desktop\yt\node_modules\bitprophet\bitprophet.js:292:28
    at binance.balance (C:\Users\AT\Desktop\yt\node_modules\bitprophet\exchange_utils.js:102:5)
    at C:\Users\AT\Desktop\yt\node_modules\node-binance-api\node-binance-api.js:1254:33
    at Request._callback (C:\Users\AT\Desktop\yt\node_modules\node-binance-api\node-binance-api.js:190:20)
    at Request.self.callback (C:\Users\AT\Desktop\yt\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\AT\Desktop\yt\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\AT\Desktop\yt\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)"
}
```

thank you

**Comment by jaggedsoft** [comment]
Thanks for your report!
You're not using the current version because that line of code now reads `Binance.options.verbose`
We're on `v0.8.3` and I'm certain you are still on version 0.7.x Please re-file if it happens on the current version. Thanks!
