### ISSUE TITLE
unable to run any method

### ISSUE THREAD

**Issue by thaison316** [jaggedsoft/node-binance-api#35]
I'm just trying to get this up and running, but done of the example works.

i get the following:
```

const publicRequest = function(url, data, callback, method = "GET") {
	                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/chungtinhlakho/Desktop/thaison/ct/app.js:4:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by jaggedsoft** [comment]
What version of node are you using?

**Comment by thaison316** [comment]
5.6.0

thanks for the quick response

**Comment by jaggedsoft** [comment]
Is it possible for you to update your node? I am running v8.4.0

**Comment by thaison316** [comment]
you're right.  updated to 8.4 and it worked.

thanks

**Comment by johnozbay** [comment]
I'm afraid I'm having a similar problem, and I can't update the version of Node. 

```
Uncaught SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

Currently I'm working on an Electron application, which even at its most beta version ( 1.8.2-beta.3) supports as high as Node 8.2.1. 

Considering there could be many others who might want to try to package a desktop toolkit that uses this API is there any chance we could work together to try to build support at least down to Node 8.2.1 ?

**Comment by jaggedsoft** [comment]
@johnozbay Did this happen only as of the last update? It could be due to our use of the spread operator.

I am using node v8.4.0 and the LTS (long term support) is already up to v8.9.4

**Comment by johnozbay** [comment]
@jaggedsoft Unfortunately I've joined the party recently and freshly for the first time yesterday. So not sure about the update. 

With regards to Node versioning, Electron (which is what's powering Github's Atom, Slack, Whatsapp desktop etc.) [isn't following Node versions as closely.](https://github.com/electron/electron/issues/9970)

**Comment by jaggedsoft** [comment]
I have rolled back the breaking change and will create a full release tomorrow. All the code is updated

**Comment by johnozbay** [comment]
That has got to be the fastest response time I've ever seen on github. Many thanks @jaggedsoft!

**Comment by qishuo** [comment]
I had the same issue. 
SyntaxError: Unexpected token ...
      at exports.runInThisContext (vm.js:53:16)
      at Module._compile (module.js:373:25)
      at Object.Module._extensions..js (module.js:416:10)
      at Module.load (module.js:343:32)
      at Function.Module._load (module.js:300:12)
      at Module.require (module.js:353:17)
      at require (internal/module.js:12:17)

**Comment by jaggedsoft** [comment]
@qishuo what version of node are you running? sounds ancient

**Comment by qishuo** [comment]
v8.10.0

**Comment by qishuo** [comment]
@jaggedsoft v8.10.0

**Comment by jaggedsoft** [comment]
I'm running v8.4.0, but I think the ES6 spread operator has been supported for over 3 years now

**Comment by qishuo** [comment]
@jaggedsoft  I can't update the version of Node. I clone release v0.3.5?

**Comment by jaggedsoft** [comment]
what environment are you using this in?

If all else fails you can run this on a vps (such as vultr, digitalocean, lunanode, etc) starting at $3 per month
