### ISSUE TITLE
Get balance from specific coin with a Var:

### ISSUE THREAD

**Issue by Woutvan** [jaggedsoft/node-binance-api#374]
Hi,

This will be a silly question, but i'm stuck so... :-)

I want to get the balance from a specific coin and want to use this code:

```
  var coin = "BLZ";

  binance.balance((error, balances) => {
    if ( error ) return console.error(error);
    console.log(coin);
    console.log(coin + " balance: ", balances.coin.available);
  });
```

But this doesn't seem to work. I always get the following error:

```
BLZ
C:\Users\xxxx\Desktop\node\test.js:12
    console.log(coin + " balance: ", balances.coin.available);
                                                   ^

TypeError: Cannot read property 'available' of undefined
    at C:\Users\xxxx\Desktop\node\test.js:12:52
    at C:\Users\xxxx\Desktop\node\node_modules\node-binance-api\node-binance-api.js:1469:31
    at Request._callback (C:\Users\xxxx\Desktop\node\node_modules\node-binance-api\node-binance-api.js:110:16)
    at Request.self.callback (C:\Users\xxxx\Desktop\node\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (C:\Users\xxxx\Desktop\node\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (C:\Users\xxxx\Desktop\node\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
```

What am I doing wrong and how can I solve this silly issue? Or do I need to use another command to get the current balance from a certain coin?

Thanks!

**Comment by jaggedsoft** [comment]
`balances[coin].available` let me know if you still need help
