### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by joelrich** [jaggedsoft/node-binance-api#389]
Sometimes I get the following error:

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/valx/valx_node/node_modules/node-binance-api/node-binance-api.js:381:82)
    at Request.self.callback (/home/valx/valx_node/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (/home/valx/valx_node/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (/home/valx/valx_node/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1161:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

Unfortunately, I don't know for which API call this happens, but I suppose that it is a futures API.

My guess is that the API returns HTML and then the JSON parsing here fails:

```
if ( typeof response.body !== 'undefined' ) return resolve( JSON.parse( response.body ) );
```

**Comment by joelrich** [comment]
I have added some logging and will update the issue if this happens again. Anyway, I think a simply try-catch around the parsing would help a lot. Right now, this leads to an uncaught exception, which is really bad.

**Comment by joelrich** [comment]
It has just happened again:
```
url = https://fapi.binance.com/fapi/v1/order?symbol=BATUSDT&side=BUY...
request.statusCode = 502
body = response.body = 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>502 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The origin closed the connection.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: XR-hHydLrN2TkgZl667frzYcniDoYrK5iu4BLTD7hS1uy2VGR-6K8w==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

```

**Comment by jaggedsoft** [comment]
thank you for your report, this was hopefully fixed in the latest update

v0.10.4 @ https://github.com/jaggedsoft/node-binance-api/commit/9fafb260e1e0d473517931cbcae7dcc853aff340

**Comment by joelrich** [comment]
Thank you!
