### ISSUE TITLE
depthData error for new listed pair

### ISSUE THREAD

**Issue by jsappme** [jaggedsoft/node-binance-api#39]
Trying to run:

```
binance.websockets.depthCache([data.symbols[i].symbol], (symbol, depth) => {
				lasttimestamp = Date.now()
				let bids = binance.sortBids(depth.bids, max);
				let asks = binance.sortAsks(depth.asks, max);
```
For APPCBTC and I get this error:

```
APPCBTC
2018-01-06T21:34:10.102657+00:00 app[web.1]: /app/node_modules/node-binance-api/node-binance-api.js:265
2018-01-06T21:34:10.102667+00:00 app[web.1]: 		for ( obj of data.bids ) {
2018-01-06T21:34:10.102668+00:00 app[web.1]: 		                  ^
2018-01-06T21:34:10.102670+00:00 app[web.1]: 
2018-01-06T21:34:10.102671+00:00 app[web.1]: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
2018-01-06T21:34:10.102673+00:00 app[web.1]:     at depthData (/app/node_modules/node-binance-api/node-binance-api.js:265:21)
2018-01-06T21:34:10.102674+00:00 app[web.1]:     at /app/node_modules/node-binance-api/node-binance-api.js:598:28
2018-01-06T21:34:10.102675+00:00 app[web.1]:     at Request._callback (/app/node_modules/node-binance-api/node-binance-api.js:41:20)
2018-01-06T21:34:10.102676+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:186:22)
2018-01-06T21:34:10.102677+00:00 app[web.1]:     at emitTwo (events.js:126:13)
2018-01-06T21:34:10.102678+00:00 app[web.1]:     at Request.emit (events.js:214:7)
2018-01-06T21:34:10.102679+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1163:10)
2018-01-06T21:34:10.102680+00:00 app[web.1]:     at emitOne (events.js:116:13)
2018-01-06T21:34:10.102681+00:00 app[web.1]:     at Request.emit (events.js:211:7)
2018-01-06T21:34:10.102682+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1085:12)
```

**Comment by jsappme** [comment]
Is there a way to catch those errors so it wont break the exec of the code?

**Comment by jaggedsoft** [comment]
Yeah i will add error handling to these functions, thank you for the suggestion

Can you please verify that your `max` parameter is set to something (like 500?)
If not just remove it
```js
				let bids = binance.sortBids(depth.bids);
				let asks = binance.sortAsks(depth.asks);
```

**Comment by jaggedsoft** [comment]
Actually it looks like error handling on this function was already included in the last release
