### ISSUE TITLE
reqHandler - response is undefined on ETIMEOUT error

### ISSUE THREAD

**Issue by tommuhm** [jaggedsoft/node-binance-api#446]
response and body is undefined in the reqHandler method(line 149) when an 'ETIMEOUT' error from the request-library occurs.

This leads to a property access of an undefined variable and crashes the program: 
```.../node_modules/node-binance-api/node-binance-api.js:151
Binance.info.lastURL = response.request.uri.href;
                                ^
TypeError: Cannot read property 'request' of undefined
    at Request._callback (.../node_modules/node-binance-api/node-binance-api.js:151:41)
    at self.callback (.../node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (.../node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

possible fix: add `if (response)` check:
```js
    const reqHandler = cb => ( error, response, body ) => {
        if ( response ) {
           Binance.info.lastRequest = new Date().getTime();
           Binance.info.lastURL = response.request.uri.href;
           Binance.info.statusCode = response.statusCode;
           Binance.info.usedWeight = response.headers['x-mbx-used-weight-1m'] || 0;
           Binance.info.orderCount1s = response.headers['x-mbx-order-count-1s'] || 0;
           Binance.info.orderCount1m = response.headers['x-mbx-order-count-1m'] || 0;
           Binance.info.orderCount1h = response.headers['x-mbx-order-count-1h'] || 0;
           Binance.info.orderCount1d = response.headers['x-mbx-order-count-1d'] || 0;
        }
        if ( !cb ) return;
        if ( error ) return cb( error, {} );
        if ( response && response.statusCode !== 200 ) return cb( response, {} );
        return cb( null, JSON.parse( body ) );
    }
```
or set Binance response infos later:

```js
    const reqHandler = cb => ( error, response, body ) => {
        if ( !cb ) return;
        if ( error ) return cb( error, {} );
        Binance.info.lastRequest = new Date().getTime();
        Binance.info.lastURL = response.request.uri.href;
        Binance.info.statusCode = response.statusCode;
        Binance.info.usedWeight = response.headers['x-mbx-used-weight-1m'] || 0;
        Binance.info.orderCount1s = response.headers['x-mbx-order-count-1s'] || 0;
        Binance.info.orderCount1m = response.headers['x-mbx-order-count-1m'] || 0;
        Binance.info.orderCount1h = response.headers['x-mbx-order-count-1h'] || 0;
        Binance.info.orderCount1d = response.headers['x-mbx-order-count-1d'] || 0;
        if ( response && response.statusCode !== 200 ) return cb( response, {} );
        return cb( null, JSON.parse( body ) );
    }
```

**Comment by jaggedsoft** [comment]
This was already fixed I guess I just forgot to publish a new release
thanks for sharing

https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L151

**Comment by tommuhm** [comment]
Thanks for the fast reply :) 

Just checked the code and I think that the problem might also exist with the `headers` property. I'm currently testing the new code and will let you know if it crashes again.

**Comment by jaggedsoft** [comment]
yeah I think you're right! good catch. I'll apply your fix

**Comment by tommuhm** [comment]
Yep just confirmed that the same problem exists for the lines: 152-157

Stacktrace:
```
.../node_modules/node-binance-api/node-binance-api.js:152
        Binance.info.statusCode = response.statusCode;
                                           ^
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (.../node_modules/node-binance-api/node-binance-api.js:152:44)
    at self.callback (.../node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (.../node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
```

**Comment by jaggedsoft** [comment]
https://github.com/jaggedsoft/node-binance-api/commit/3894b876443aec89e3787f52ebb32a03f34fbdfb
