### ISSUE TITLE
Faced with a crash two times. Suggestion: looks responseCode is absent sometimes.

### ISSUE THREAD

**Issue by ProgrammingLife** [jaggedsoft/node-binance-api#449]
```
/home/user/scripts/3rd-party/node-binance-api/node-binance-api.js:152
        Binance.info.statusCode = response.statusCode;
                                            ^
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/user/scripts/3rd-party/node-binance-api/node-binance-api.js:152:44)
    at self.callback (/home/user/scripts/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/home/user/scripts/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Looks we need something like that on the line 152: 
`Binance.info.statusCode = response.statusCode || 0;`

Because sometimes statusCode can be missed. Don't know why.

And yeah why didn't it fall just to undefined value? Why did it crash?

**Comment by jaggedsoft** [comment]
thank you 👍

**Comment by jaggedsoft** [comment]
https://github.com/jaggedsoft/node-binance-api/commit/7b67119f8c75124cdc35c4324e62e973592738a3
