### ISSUE TITLE
why exchangeInfo public request need APIKEY

### ISSUE THREAD

**Issue by jianxinss** [jaggedsoft/node-binance-api#451]
`const Binance = require('node-binance-api');
const client_ = new Binance(); 
client_.exchangeInfo(function (error, response) {}))`

/mount/project/binanceRobot/node_modules/node-binance-api/node-binance-api.js:176
        if ( !Binance.options.APIKEY ) throw Error( 'apiRequest: Invalid API Key' );
                                       ^

Error: apiRequest: Invalid API Key
    at apiRequest (/mount/project/binanceRobot/node_modules/node-binance-api/node-binance-api.js:176:46)
    at Object.userData (/mount/project/binanceRobot/node_modules/node-binance-api/node-binance-api.js:2771:17)
    at Object.<anonymous> (/mount/project/binanceRobot/sub_330060/task_330060.js:16:19)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11

"node-binance-api": "0.10.4" no problem
"node-binance-api": "0.10.7" is not OK

**Comment by jaggedsoft** [comment]
tested working in `v0.11.8`
