### ISSUE TITLE
Syntax Error in NPM version of the API 

### ISSUE THREAD

**Issue by slavkobojanic** [jaggedsoft/node-binance-api#51]
```
/Users/slavko/Desktop/Code/NodeJS/CryptoHub/node_modules/node-binance-api/node-binance-api.js:431
		marketSell: function(symbol, quantity, flags = {type: 'MARKET'} callback = false) {
		                                                                ^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/slavko/Desktop/Code/NodeJS/CryptoHub/routes/index.js:2:15)
```

In the NPM version on line 431 there's a missing comma, which seems to be present in the most recent GitHub commit but isn't present in the latest NPM version.

Just letting ya know :)

**Comment by jaggedsoft** [comment]
Thank you very much, incrementing version number
