### ISSUE TITLE
The start of this repo

### ISSUE THREAD

**Issue by rickllyxu** [jaggedsoft/node-binance-api#511]
Hello, sorry to disturb you. 
I run the following code, and show the `opt` in `Binance().options` function, however, it said opt is `{}`, and then I get timeout error. it is "at listOnTimeout (internal/timers.js:554:17)   at processTimers (internal/timers.js:497:7)"
```
const Binance = require( '../node-binance-api' );
const opt = {
    APIKEY: 'xxxx',
    APISECRET: 'yyyy'
}
const binance = new Binance().options( opt );

// Getting latest price of a symbol
binance.prices( 'BNBBTC', ( error, ticker ) => {
    console.info( "Price of BNB: ", ticker.BNBBTC );
} );
```
Can you help me?

**Comment by dbvcode** [comment]
Try adding `useServerTime: true` in opt 
This was the original comment on an older version of the api:

>useServerTime: true // If you get timestamp errors, synchronize to server time at startup

**Comment by jaggedsoft** [comment]
Yeah its best to use async/await and then you can just "await binance.useServerTime();"

otherwise you have to do a callback like this https://github.com/jaggedsoft/node-binance-api/blob/master/examples/fix-timestamp-error.js

```js
(async () => {
const Binance = require( 'node-binance-api' )
const binance = new Binance( { APIKEY:'xx', APISECRET:'oo' } )
await binance.useServerTime();

// Getting latest price of a symbol
binance.prices( 'BNBBTC', ( error, ticker ) => {
    console.info( "Price of BNB: ", ticker.BNBBTC );
} );

})();
```

if you still have problems try this, automatic exception reporting
`process.on( 'unhandledRejection', up => { throw up } )`

if your server is ipv6 only, you might need to set `{ family: 6 }` option

if your IP is banned by binance, you might need to use a proxy or set `localAddress` to another interface IP
