### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined 

### ISSUE THREAD

**Issue by robertbodley** [jaggedsoft/node-binance-api#58]
HI,

I have tried to figure out why this happens but for some reason everything I try doesn't work. This error does not always occur but a lot of the time does.

Any help would be appreciated! 

```
/home/sites/pndbot.com/public/v1/node_modules/node-binance-api/node-binance-api.js:220
	for ( let obj of data.balances ) {
		                   ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at balanceData (/home/sites/pndbot.com/public/v1/node_modules/node-binance-api/node-binance-api.js:220:22)
    at /home/sites/pndbot.com/public/v1/node_modules/node-binance-api/node-binance-api.js:485:30
    at Request._callback (/home/sites/pndbot.com/public/v1/node_modules/node-binance-api/node-binance-api.js:85:20)
    at Request.self.callback (/home/sites/pndbot.com/public/v1/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/sites/pndbot.com/public/v1/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/sites/pndbot.com/public/v1/node_modules/request/request.js:1085:12)
```

**Comment by jaggedsoft** [comment]
Thanks for the report!
are you using the latest version? I thought this bug was fixed
any more info you can provide? what does the code look like to pull balances?

**Comment by robertbodley** [comment]
I have now made my recvWindow: 6000000 and it finally works for the time being. Is there any other way I could fix this? or is that method okay?

Thanks for the quick response!

**Comment by jaggedsoft** [comment]
Sounds like you might need to sync your system time, binance will error out requests if the time difference is too much
60000 is the default, should mean it gives it 60 seconds before it times out, but if its working for you i dont see anything wrong with a higher value
likewise thank you :)

**Comment by robertbodley** [comment]
Okay, makes sense.

Thanks again for the help!
