### ISSUE TITLE
RSV2 and RSV3 must be clear 

### ISSUE THREAD

**Issue by kyletan7** [jaggedsoft/node-binance-api#60]
I'm streaming data from the websocket, but always get this error after 4-5 minutes of running it:
This is the ws method I'm using:

```
    binance.websockets.prevDay(false, function(response) {
    });
```

```
Parse error: Unexpected token ║ in JSON at position 51198
error: uncaughtException: RSV2 and RSV3 must be clear
    at Receiver.getInfo (\node_modules\ws\lib\Receiver.js:184:18)
    at Receiver.startLoop (\node_modules\ws\lib\Receiver.js:153:16)
    at Receiver.add (\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket._ultron.on (\node_modules\ws\lib\WebSocket.js:138:22)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
```
Any idea what might be causing it?

**Comment by jaggedsoft** [comment]
Hmm, never heard of either of those errors. Trying to think of a potential solution
1. Some sort of special symbol in the JSON file, maybe we can catch that error
2. perhaps catch the websocket exception

**Comment by kyletan7** [comment]
Right now just    ```
binance.websockets.prevDay(false, function(response) {
    });
```

crashes after a while. Maybe something is up with Binance's response?
