### ISSUE TITLE
0.4.0:  TypeError: Cannot read property 'msg' of null

### ISSUE THREAD

**Issue by keyle** [jaggedsoft/node-binance-api#62]
Version 0.4.0 

L.146
```
node_modules\node-binance-api\node-binance-api.js:146
                        if ( typeof response.msg !== 'undefined' && response.msg === 'Filter failure: MIN_NOTIONAL' ) {
                                             ^

TypeError: Cannot read property 'msg' of null
    at node_modules\node-binance-api\node-binance-api.js:146:25
    at Request._callback (S:\Projects\prophet\node_modules\node-binance-api\node-binance-api.js:111:12)
    at Request.self.callback (S:\Projects\prophet\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (S:\Projects\prophet\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (S:\Projects\prophet\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

I believe the problem is at L.108
https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L108

you're sending null as response, L.149 probably needs to implement the new pattern of `(error, response)` instead of `(response)`

**Comment by jaggedsoft** [comment]
Thank you

**Comment by keyle** [comment]
Line 145 same issue (response) instead of (error, response)
Line 483 as well :)

**Comment by jaggedsoft** [comment]
Thanks again. `v0.4.2` is now live and ready for testing
https://github.com/jaggedsoft/node-binance-api/commit/6477b147f78d035a6b706763af06fe9ca0f35a19

**Comment by keyle** [comment]
what about this one? 
https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L480

**Comment by keyle** [comment]
No problem! 
I prefer a library that breaks and release often, than a library that is slow to update!
