### ISSUE TITLE
TypeError: data.reduce is not a function on futuresDaily()

### ISSUE THREAD

**Issue by jmarrr** [jaggedsoft/node-binance-api#623]
I was running a script with `let stat = await binance.futuresDaily();` and it is always giving me this exception

```
TypeError: data.reduce is not a function
    at Object.futuresDaily (C:\Users\xx\OneDrive\Desktop\xx\node_modules\node-binance-api\node-binance-api.js:3883:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Timeout.afterBurst [as _onTimeout] (C:\Users\xx\OneDrive\Desktop\xx\xx\xx.js:154:15)
```

this always persist and have no idea why it happens.

**Comment by jonasmello** [comment]
+1

**Comment by carlosmiei** [comment]
@jonasmello we're going to take a look and get back to you

**Comment by carlosmiei** [comment]
@jonasmello what's your node-binance-api version?
On my end, seems to be working fine

```


async function main() {
	const binance = new Binance()
	const res = await binance.futuresDaily()
	console.log(res)
}

```

result

```
{
  PONKEUSDT: [Object: null prototype] {
    symbol: 'PONKEUSDT',
    priceChange: '-0.0008400',
    priceChangePercent: '-0.616',
    weightedAvgPrice: '0.1338141',
    lastPrice: '0.1354400',
    lastQty: '122',
    openPrice: '0.1362800',
    highPrice: '0.1407200',
    lowPrice: '0.1259400',
    volume: '64845407',
    quoteVolume: '8677227.2457200',
    openTime: 1740582660000,
    closeTime: 1740669095796,
    firstId: 23991947,
    lastId: 24150657,
    count: 158711
  },
  ATAUSDT: [Object: null prototype] {
    symbol: 'ATAUSDT',
    priceChange: '0.0011',
    priceChangePercent: '1.824',
    weightedAvgPrice: '0.0600',
    lastPrice: '0.0614',
    lastQty: '111',
    openPrice: '0.0603',
    highPrice: '0.0624',
    lowPrice: '0.0567',
    volume: '116459370',
```
