### ISSUE TITLE
Error: Unexpected server response: 504

### ISSUE THREAD

**Issue by jsappme** [jaggedsoft/node-binance-api#65]
any idea what could cause this error?
```
events.js:183
2018-01-20T03:55:13.804223+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2018-01-20T03:55:13.804224+00:00 app[web.1]:       ^
2018-01-20T03:55:13.804225+00:00 app[web.1]: 
2018-01-20T03:55:13.804226+00:00 app[web.1]: Error: Unexpected server response: 504
2018-01-20T03:55:13.804227+00:00 app[web.1]:     at ClientRequest._req.on (/app/node_modules/ws/lib/websocket.js:645:21)
2018-01-20T03:55:13.804228+00:00 app[web.1]:     at emitOne (events.js:116:13)
2018-01-20T03:55:13.804229+00:00 app[web.1]:     at ClientRequest.emit (events.js:211:7)
2018-01-20T03:55:13.804231+00:00 app[web.1]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
2018-01-20T03:55:13.804232+00:00 app[web.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
2018-01-20T03:55:13.804233+00:00 app[web.1]:     at TLSSocket.socketOnData (_http_client.js:440:20)
2018-01-20T03:55:13.804235+00:00 app[web.1]:     at emitOne (events.js:116:13)
2018-01-20T03:55:13.804235+00:00 app[web.1]:     at TLSSocket.emit (events.js:211:7)
2018-01-20T03:55:13.804237+00:00 app[web.1]:     at addChunk (_stream_readable.js:263:12)
2018-01-20T03:55:13.804238+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:250:11)
```

**Comment by jaggedsoft** [comment]
Response 504 is a gateway timeout error. I've been getting these every once in awhile too. Not sure the best way to handle these situations
Make sure you're not opening too many connections too fast - my delay is 150ms or more between new requests/websocket connections
