### ISSUE TITLE
Incorrect Api Error case Not Handled

### ISSUE THREAD

**Issue by azharuniverse** [jaggedsoft/node-binance-api#70]
`TypeError: Cannot read property 'balances' of undefined
    at balanceData (C:\Users\azhar\Documents\Projects\MarsTrade\node_modules\node-binance-api\node-binance-api.js:268:19)
    at C:\Users\azhar\Documents\Projects\MarsTrade\node_modules\node-binance-api\node-binance-api.js:568:38
    at Request._callback (C:\Users\azhar\Documents\Projects\MarsTrade\node_modules\node-binance-api\node-binance-api.js:106:12)
    at Request.self.callback (C:\Users\azhar\Documents\Projects\MarsTrade\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\azhar\Documents\Projects\MarsTrade\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\azhar\Documents\Projects\MarsTrade\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by azharuniverse** [comment]
Solution:
line 268: `if( typeof  data === 'undefined') return {};`

**Comment by jaggedsoft** [comment]
Thank you
