### ISSUE TITLE
cancelAll(symbol), cancelOrders(symbol) CRASH if there is no active order for a symbol

### ISSUE THREAD

**Issue by neviko** [jaggedsoft/node-binance-api#720]
TypeError: json is not iterable
    at \node_modules\node-binance-api\node-binance-api.js:3074:42
    at Request._callback (\node_modules\node-binance-api\node-binance-api.js:186:29)
    at self.callback (\node_modules\request\request.js:185:22)
    at Request.emit (events.js:205:15)
    at Request.onRequestError (\node_modules\request\request.js:877:8)

**Comment by Syerna** [comment]
Oh, you have a more precise use case for https://github.com/jaggedsoft/node-binance-api/issues/709
