### ISSUE TITLE
Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by TomToms55** [jaggedsoft/node-binance-api#778]
Been running 24/7 the futures WebSockets in a VPS with no problems. Yesterday the following has happened:
 I am also using ccxt and that request had a timeout, probably Binance API was down or any network problems in the VPS, but still the "Cannot read property 'join' of undefined" from node-binance-api.js shouldn't happen.
 
```log
2021-12-20T00:25:35: [ 'Futures WebSocket closed: !miniTicker@arr (1006)' ]
2021-12-20T00:25:35: [ 'Futures WebSocket reconnecting: !miniTicker@arr...' ]
2021-12-20T02:17:35: [ 'Futures WebSocket closed: 1065495013 (1006)' ]
2021-12-20T02:17:35: [ 'Futures WebSocket reconnecting: 1065495013...' ]
2021-12-20T02:18:35: [ 'Futures WebSocket closed: !miniTicker@arr (1006)' ]
2021-12-20T02:18:35: [ 'Futures WebSocket reconnecting: !miniTicker@arr...' ]
2021-12-20T02:18:35: [ 'Futures WebSocket closed: 1065495013 (1006)' ]
2021-12-20T02:18:35: [ 'Futures WebSocket reconnecting: 1065495013...' ]
2021-12-20T02:20:05: [ 'Futures WebSocket closed: 1065495013 (1006)' ]
2021-12-20T02:20:05: [ 'Futures WebSocket reconnecting: 1065495013...' ]
2021-12-20T02:20:35: [
2021-12-20T02:20:35:   'Futures WebSocket closed: qAWYon07iqNWT2MugbaiEuxavhKK1d8WBEo7DwCyBxgGXqKLYtuA2Z0AfRpS0l4E (1006)'
2021-12-20T02:20:35: ]
2021-12-20T02:20:35: [
2021-12-20T02:20:35:   'Futures WebSocket reconnecting: qAWYon07iqNWT2MugbaiEuxavhKK1d8WBEo7DwCyBxgGXqKLYtuA2Z0AfRpS0l4E...'
2021-12-20T02:20:35: ]
2021-12-20T02:20:45: TypeError: Cannot read property 'join' of undefined
2021-12-20T02:20:45:     at futuresSubscribe (/root/my_project/node_modules/node-binance-api/node-binance-api.js:932:37)
2021-12-20T02:20:45:     at /root/my_project/node_modules/node-binance-api/node-binance-api.js:5419:42
2021-12-20T02:20:45:     at Request._callback (/root/my_project/node_modules/node-binance-api/node-binance-api.js:186:29)
2021-12-20T02:20:45:     at self.callback (/root/my_project/node_modules/request/request.js:185:22)
2021-12-20T02:20:45:     at Request.emit (events.js:326:22)
2021-12-20T02:20:45:     at ClientRequest.<anonymous> (/root/my_project/node_modules/request/request.js:819:16)
2021-12-20T02:20:45:     at Object.onceWrapper (events.js:420:28)
2021-12-20T02:20:45:     at ClientRequest.emit (events.js:314:20)
2021-12-20T02:20:45:     at TLSSocket.emitRequestTimeout (_http_client.js:715:9)
2021-12-20T02:20:45:     at Object.onceWrapper (events.js:420:28)
2021-12-20T02:20:46: Restarting Server
2021-12-20T02:20:56: RequestTimeout: binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1639966846870&recvWindow=5000&signature=4fba47e2f69d52a37d3ab1cc899878faba1b1a85833efbb4acd67436475b57ee request timed out (10000 ms)
2021-12-20T02:20:56:     at /root/my_project/node_modules/ccxt/js/base/Exchange.js:438:27
2021-12-20T02:20:56:     at binance.request (/root/my_project/node_modules/ccxt/js/binance.js:4813:26)
2021-12-20T02:20:56:     at binance.fetchCurrencies (/root/my_project/node_modules/ccxt/js/binance.js:968:26)
2021-12-20T02:20:56:     at binance.loadMarketsHelper (/root/my_project/node_modules/ccxt/js/base/Exchange.js:736:26) {
2021-12-20T02:20:56:   constructor: [class RequestTimeout extends NetworkError]
2021-12-20T02:20:56: }
```

**Comment by ordimans** [comment]
Same here, one time by day...

No solution ? Even with a try catch, and restart WS ?
