### ISSUE TITLE
Failing initializing userFuterData stream

### ISSUE THREAD

**Issue by beratuslu** [jaggedsoft/node-binance-api#823]
Can anyone tell me what is wrong here?

```
const BinanceClient = require("node-binance-api");
const binance = new BinanceClient().options({
  APIKEY: "KEY",
  APISECRET: "ANOTHER_KEY",
});

binance.websockets.userFutureData(console.log, console.log, console.log);
```

Error I am getting:
```

/Users/beratuslu/Desktop/futuresTest/node_modules/node-binance-api/node-binance-api.js:932
        const queryParams = streams.join( '/' );
                                    ^

TypeError: Cannot read properties of undefined (reading 'join')
    at futuresSubscribe (/Users/beratuslu/Desktop/futuresTest/node_modules/node-binance-api/node-binance-api.js:932:37)
    at /Users/beratuslu/Desktop/futuresTest/node_modules/node-binance-api/node-binance-api.js:5419:42
    at Request._callback (/Users/beratuslu/Desktop/futuresTest/node_modules/node-binance-api/node-binance-api.js:187:63)
    at Request.self.callback (/Users/beratuslu/Desktop/futuresTest/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/Users/beratuslu/Desktop/futuresTest/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/Users/beratuslu/Desktop/futuresTest/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
```

**Comment by holyoops** [comment]
guess it failed when requesting the v1/listenKey interface, you got an error but no listenKey, made the streams undefined
you can add console log at line 5403 in node-binance-api.js to figure out

**Comment by elihaidv** [comment]
Same here.
I realized the problem is invalid API keys.
But I wonder how can I catch this.
It seems try/catch doesn't work. My process is crash.

**Comment by elihaidv** [comment]
Here my fix
https://github.com/jaggedsoft/node-binance-api/pull/805
